[settings]
minimum_release_age_excludes = ["codex", "gh", "npm:@opencode-ai/cli"]

[settings.npm]
package_manager = "npm"

[tools]
bun = "latest"
codex = "latest"
gh = "latest"
"npm:@xai-official/grok" = { version = "latest", allow_builds = ["@xai-official/grok"], npm_args = "--min-release-age-exclude=@xai-official/*" }
"npm:@opencode-ai/cli" = { version = "beta", allow_builds = ["@opencode-ai/cli"], npm_args = "--min-release-age-exclude=@opencode-ai/*" }
"npm:mux-sesh" = "latest"
"npm:@quietghost/x-cli" = { version = "latest", allow_builds = ["@quietghost/x-cli"] }
opencode = "latest"
pi = "latest"
deno = "latest"
flutter = "latest"
go = "latest"
java = "latest"
python = "latest"
ruby = "latest"
"npm:@kitlangton/ghui" = "latest"
zig = "latest"
zls = "latest"
node = "latest"
claude = "latest"
"npm:playwright" = "latest"
