--ozone-platform-hint=wayland
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiIgnoreDriverChecks,VaapiOnNvidiaGPUs
--ignore-gpu-blocklist
--load-extension=/usr/share/omarchy/default/chromium/extensions/yt-dlp
