#!/bin/bash

# Web App Installer for Arch Linux Menu System

if [ "$#" -ne 3 ]; then
  echo -e "\e[34mLet's create a new web app you can start with the app launcher.\n\e[0m"
  APP_NAME=$(gum input --prompt "Name> " --placeholder "My favorite web app")
  APP_URL=$(gum input --prompt "URL> " --placeholder "https://example.com")
  ICON_URL=$(gum input --prompt "Icon URL> " --placeholder "See https://dashboardicons.com (must use PNG!)")
else
  APP_NAME="$1"
  APP_URL="$2"
  ICON_URL="$3"
fi

if [[ -z "$APP_NAME" || -z "$APP_URL" || -z "$ICON_URL" ]]; then
  echo "You must set app name, app URL, and icon URL!"
  exit 1
fi

ICON_DIR="$HOME/.local/share/applications/icons"
DESKTOP_FILE="$HOME/.local/share/applications/$APP_NAME.desktop"
ICON_PATH="$ICON_DIR/$APP_NAME.png"

mkdir -p "$ICON_DIR"

if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
  echo "Error: Failed to download icon."
  exit 1
fi

# Always use Chrome for web apps
browser_cmd="chromium --app=\"$APP_URL\""

cat >"$DESKTOP_FILE" <<EOFDESKTOP
[Desktop Entry]
Version=1.0
Name=$APP_NAME
Comment=$APP_NAME
Exec=$browser_cmd
Terminal=false
Type=Application
Icon=$ICON_PATH
StartupNotify=true
EOFDESKTOP

chmod +x "$DESKTOP_FILE"

if [ "$#" -ne 3 ]; then
  echo -e "\nYou can now find $APP_NAME using the app launcher (SUPER + SPACE)\n"
  echo "To create a keybinding, add this to your Hyprland config:"
  echo "bind = SUPER, <key>, exec, $browser_cmd"
fi
