# Extra autostart processes
# exec-once = uwsm app -- my-service
# Override default hypridle with our device-aware launcher
exec-once = killall hypridle 2>/dev/null || true; ~/.local/bin/hypridle-launcher
# Automatic TV/laptop display switching
exec-once = ~/.local/bin/hypr-display-monitor

windowrule = workspace 1 silent, match:class ^(legcord)$
windowrule = workspace 2 silent, match:class ^(zen)$
windowrule = workspace 4 silent, match:class ^(jetbrains-idea)$
windowrule = workspace 4 silent, match:class ^(steam)$
windowrule = workspace 4 silent, match:class ^(Cursor)$
windowrule = workspace 4 silent, match:class ^(Code)$
windowrule = workspace 5 silent, match:class ^(gimp)$
windowrule = workspace 6 silent, match:class ^(com.github.th_ch.youtube_music)$
windowrule = workspace 7 silent, match:class ^(Proton Mail)$
windowrule = workspace 8 silent, match:class ^(com.obsproject.Studio)$
windowrule = workspace 8 silent, match:class ^(de.feschber.LanMouse)$
windowrule = workspace 9 silent, match:class ^(Slack)$
windowrule = tile on, match:class ^(Chromium)$

exec-once = $terminal & hyprctl dispatch workspace 3
exec-once = hyprpm reload
exec-once = zen-browser
exec-once = legcord
exec-once = Slack
